export const SORTABLE_FIELDS = [
  'market_name',
  'category',
  'venue',
  'side',
  'avg_entry_price',
  'current_price',
  'shares',
  'cost_basis',
  'unrealized_pnl',
  'unrealized_pnl_pct',
  'exposure',
  'condition_id',
  'outcome_token_id',
  'proxy_wallet',
  'slug',
  'icon',
  'event_id',
  'event_slug',
  'outcome_index',
  'opposite_outcome',
  'opposite_asset',
  'end_date',
  'redeemable',
  'mergeable',
  'negative_risk',
  'total_bought',
  'realized_pnl',
  'percent_realized_pnl',
  'initial_value',
  'current_value',
  'percent_pnl',
] as const;

export type SortableField = (typeof SORTABLE_FIELDS)[number];
